name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Package and upload to CurseForge, Wago, WoWInterface, and GitHub
        uses: BigWigsMods/packager@v2
